/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 13 21:22:49 GMT 2022
 */

package br.edu.ufcg.computacao.eureca.backend.core.models;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import br.edu.ufcg.computacao.eureca.backend.core.models.Registration;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Registration_ESTest extends Registration_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Registration registration0 = new Registration();
      Registration registration1 = new Registration("v50;\"zx?s/2xf}Nr}Is");
      registration0.setValue("A:8iw)@seNMBW");
      int int0 = registration0.compareTo(registration1);
      assertEquals((-53), int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Registration registration0 = new Registration();
      registration0.setValue(" 9d)");
      String string0 = registration0.toString();
      assertEquals(" 9d)", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Registration registration0 = new Registration("");
      String string0 = registration0.toString();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Registration registration0 = new Registration();
      registration0.setValue(" 9d)");
      String string0 = registration0.getRegistration();
      assertEquals(" 9d)", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Registration registration0 = new Registration("");
      String string0 = registration0.getRegistration();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Registration registration0 = new Registration(")rDJ?+}P{L");
      int int0 = registration0.compareTo(registration0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Registration registration0 = new Registration();
      registration0.setValue("br.edu.ufcg.computacao.eureca.backend.core.models.Registration");
      Registration registration1 = new Registration("Kq0yyd_ZIi");
      int int0 = registration0.compareTo(registration1);
      assertEquals(23, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Registration registration0 = new Registration("");
      // Undeclared exception!
      try { 
        registration0.compareTo(registration0);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Registration registration0 = new Registration(")rDJ?+}P{L");
      // Undeclared exception!
      try { 
        registration0.compareTo(")rDJ?+}P{L");
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.String cannot be cast to br.edu.ufcg.computacao.eureca.backend.core.models.Registration
         //
         verifyException("br.edu.ufcg.computacao.eureca.backend.core.models.Registration", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Registration registration0 = new Registration();
      String string0 = registration0.getRegistration();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Registration registration0 = new Registration();
      Registration registration1 = new Registration("v5/;\"zx?s/2xf}Nr}Is");
      assertFalse(registration1.equals((Object)registration0));
      
      registration0.setValue("A:8iw)@seNMBW");
      int int0 = registration0.compareTo(registration1);
      assertEquals((-53), int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Registration registration0 = new Registration();
      Registration registration1 = new Registration("v5/;\"zx?s/2xf}Nr}Is");
      boolean boolean0 = registration1.equals(registration0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Registration registration0 = new Registration();
      boolean boolean0 = registration0.equals("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Registration registration0 = new Registration();
      boolean boolean0 = registration0.equals(registration0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Registration registration0 = new Registration();
      boolean boolean0 = registration0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Registration registration0 = new Registration();
      // Undeclared exception!
      try { 
        registration0.compareTo(registration0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("br.edu.ufcg.computacao.eureca.backend.core.models.Registration", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Registration registration0 = new Registration();
      String string0 = registration0.toString();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Registration registration0 = new Registration("");
      registration0.hashCode();
  }
}
