/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 13 20:54:42 GMT 2022
 */

package br.edu.ufcg.computacao.eureca.backend.core.models;

import org.junit.Test;
import static org.junit.Assert.*;
import br.edu.ufcg.computacao.eureca.backend.core.models.SubjectScheduleKey;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SubjectScheduleKey_ESTest extends SubjectScheduleKey_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SubjectScheduleKey subjectScheduleKey0 = new SubjectScheduleKey("br.edu.ufcg.computacao.eureca.backend.core.models.SubjectScheduleKey", "2Nk-8#", "cDV7}d]1", (String) null);
      String string0 = subjectScheduleKey0.getTerm();
      assertEquals("2Nk-8#", subjectScheduleKey0.getCurriculumCode());
      assertNull(string0);
      assertEquals("cDV7}d]1", subjectScheduleKey0.getSubjectCode());
      assertEquals("br.edu.ufcg.computacao.eureca.backend.core.models.SubjectScheduleKey", subjectScheduleKey0.getCourseCode());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SubjectScheduleKey subjectScheduleKey0 = new SubjectScheduleKey("YJ]Sj QmYWig!6", "Q-09fAq-W&;x@t*u", "YJ]Sj QmYWig!6", "YJ]Sj QmYWig!6");
      assertEquals("YJ]Sj QmYWig!6", subjectScheduleKey0.getTerm());
      
      subjectScheduleKey0.setTerm("");
      subjectScheduleKey0.getTerm();
      assertEquals("Q-09fAq-W&;x@t*u", subjectScheduleKey0.getCurriculumCode());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SubjectScheduleKey subjectScheduleKey0 = new SubjectScheduleKey("", (String) null, (String) null, "");
      String string0 = subjectScheduleKey0.getSubjectCode();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SubjectScheduleKey subjectScheduleKey0 = new SubjectScheduleKey((String) null, (String) null, (String) null, "");
      subjectScheduleKey0.setSubjectCode("o)^F");
      String string0 = subjectScheduleKey0.getSubjectCode();
      assertEquals("o)^F", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SubjectScheduleKey subjectScheduleKey0 = new SubjectScheduleKey("", (String) null, (String) null, "");
      String string0 = subjectScheduleKey0.getCurriculumCode();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SubjectScheduleKey subjectScheduleKey0 = new SubjectScheduleKey("", "", "", "");
      subjectScheduleKey0.setCourseCode((String) null);
      String string0 = subjectScheduleKey0.getCourseCode();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SubjectScheduleKey subjectScheduleKey0 = new SubjectScheduleKey("", "", "", "eFx_K-8G@~]EP9");
      assertEquals("", subjectScheduleKey0.getCourseCode());
      
      subjectScheduleKey0.setCourseCode("&v)Q");
      subjectScheduleKey0.getCourseCode();
      assertEquals("", subjectScheduleKey0.getSubjectCode());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SubjectScheduleKey subjectScheduleKey0 = new SubjectScheduleKey("", "nEt&q_*)fSs@QZ{PN", "gYBUbmF", "gYBUbmF");
      subjectScheduleKey0.setTerm("");
      subjectScheduleKey0.setSubjectCode("");
      SubjectScheduleKey subjectScheduleKey1 = new SubjectScheduleKey("", (String) null, "\"'eb\"t-_9D$cMC.]-0U", "gYBUbmF");
      assertEquals("\"'eb\"t-_9D$cMC.]-0U", subjectScheduleKey1.getSubjectCode());
      
      subjectScheduleKey1.setSubjectCode("");
      subjectScheduleKey1.setCurriculumCode("nEt&q_*)fSs@QZ{PN");
      boolean boolean0 = subjectScheduleKey0.equals(subjectScheduleKey1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SubjectScheduleKey subjectScheduleKey0 = new SubjectScheduleKey("", "", "", "");
      SubjectScheduleKey subjectScheduleKey1 = new SubjectScheduleKey("", "", "", "");
      boolean boolean0 = subjectScheduleKey0.equals(subjectScheduleKey1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SubjectScheduleKey subjectScheduleKey0 = new SubjectScheduleKey("", "", "", "");
      SubjectScheduleKey subjectScheduleKey1 = new SubjectScheduleKey("", "", "", "");
      assertTrue(subjectScheduleKey1.equals((Object)subjectScheduleKey0));
      
      subjectScheduleKey1.setCurriculumCode("br.edu.ufcg.computacao.eureca.backend.core.models.SubjectScheduleKey");
      boolean boolean0 = subjectScheduleKey0.equals(subjectScheduleKey1);
      assertFalse(subjectScheduleKey1.equals((Object)subjectScheduleKey0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SubjectScheduleKey subjectScheduleKey0 = new SubjectScheduleKey("", "", "", "");
      SubjectScheduleKey subjectScheduleKey1 = new SubjectScheduleKey("", "", "", "");
      subjectScheduleKey0.setCourseCode("br.edu.ufcg.computacao.eureca.backend.core.models.SubjectScheduleKey");
      boolean boolean0 = subjectScheduleKey0.equals(subjectScheduleKey1);
      assertFalse(subjectScheduleKey1.equals((Object)subjectScheduleKey0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SubjectScheduleKey subjectScheduleKey0 = new SubjectScheduleKey("", "", "", "eFx_K-8G@~]EP9");
      SubjectScheduleKey subjectScheduleKey1 = new SubjectScheduleKey("", "", (String) null, "");
      boolean boolean0 = subjectScheduleKey0.equals(subjectScheduleKey1);
      assertEquals("eFx_K-8G@~]EP9", subjectScheduleKey0.getTerm());
      assertEquals("", subjectScheduleKey0.getSubjectCode());
      assertEquals("", subjectScheduleKey0.getCurriculumCode());
      assertFalse(boolean0);
      assertEquals("", subjectScheduleKey0.getCourseCode());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SubjectScheduleKey subjectScheduleKey0 = new SubjectScheduleKey((String) null, (String) null, (String) null, "");
      boolean boolean0 = subjectScheduleKey0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SubjectScheduleKey subjectScheduleKey0 = new SubjectScheduleKey("GPe%]}JO?tu0*e4", "mt.", "", "");
      boolean boolean0 = subjectScheduleKey0.equals(subjectScheduleKey0);
      assertEquals("", subjectScheduleKey0.getTerm());
      assertTrue(boolean0);
      assertEquals("", subjectScheduleKey0.getSubjectCode());
      assertEquals("GPe%]}JO?tu0*e4", subjectScheduleKey0.getCourseCode());
      assertEquals("mt.", subjectScheduleKey0.getCurriculumCode());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      SubjectScheduleKey subjectScheduleKey0 = new SubjectScheduleKey("", "", "", "eFx_K-8G@~]EP9");
      boolean boolean0 = subjectScheduleKey0.equals("");
      assertFalse(boolean0);
      assertEquals("", subjectScheduleKey0.getCourseCode());
      assertEquals("", subjectScheduleKey0.getSubjectCode());
      assertEquals("", subjectScheduleKey0.getCurriculumCode());
      assertEquals("eFx_K-8G@~]EP9", subjectScheduleKey0.getTerm());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      SubjectScheduleKey subjectScheduleKey0 = new SubjectScheduleKey("", "", "", "eFx_K-8G@~]EP9");
      String string0 = subjectScheduleKey0.getTerm();
      assertEquals("", subjectScheduleKey0.getCurriculumCode());
      assertEquals("", subjectScheduleKey0.getSubjectCode());
      assertEquals("eFx_K-8G@~]EP9", string0);
      assertEquals("", subjectScheduleKey0.getCourseCode());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      SubjectScheduleKey subjectScheduleKey0 = new SubjectScheduleKey("GPe%]}JO?tu0*e4", "mt.", "", "");
      String string0 = subjectScheduleKey0.getSubjectCode();
      assertEquals("GPe%]}JO?tu0*e4", subjectScheduleKey0.getCourseCode());
      assertEquals("mt.", subjectScheduleKey0.getCurriculumCode());
      assertEquals("", string0);
      assertEquals("", subjectScheduleKey0.getTerm());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      SubjectScheduleKey subjectScheduleKey0 = new SubjectScheduleKey("", "", "", "");
      subjectScheduleKey0.hashCode();
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      SubjectScheduleKey subjectScheduleKey0 = new SubjectScheduleKey("", "", "", "");
      subjectScheduleKey0.setCurriculumCode("br.edu.ufcg.computacao.eureca.backend.core.models.SubjectScheduleKey");
      String string0 = subjectScheduleKey0.getCurriculumCode();
      assertEquals("br.edu.ufcg.computacao.eureca.backend.core.models.SubjectScheduleKey", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      SubjectScheduleKey subjectScheduleKey0 = new SubjectScheduleKey("", "", "", "");
      String string0 = subjectScheduleKey0.getCourseCode();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      SubjectScheduleKey subjectScheduleKey0 = new SubjectScheduleKey("", "", "", "");
      String string0 = subjectScheduleKey0.getCurriculumCode();
      assertEquals("", string0);
  }
}
