/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 13 21:31:06 GMT 2022
 */

package br.edu.ufcg.computacao.eureca.backend;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import br.edu.ufcg.computacao.eureca.backend.Main;
import org.apache.log4j.LogManager;
import org.apache.log4j.spi.LoggerRepository;
import org.apache.log4j.spi.RepositorySelector;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import org.springframework.boot.ApplicationArguments;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Main_ESTest extends Main_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RepositorySelector repositorySelector0 = mock(RepositorySelector.class, new ViolatedAssumptionAnswer());
      doReturn((LoggerRepository) null).when(repositorySelector0).getLoggerRepository();
      LogManager.setRepositorySelector(repositorySelector0, "java.lang.String");
      Main main0 = null;
      try {
        main0 = new Main();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.log4j.LogManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ApplicationArguments applicationArguments0 = mock(ApplicationArguments.class, new ViolatedAssumptionAnswer());
      Main main0 = new Main();
      // Undeclared exception!
      try { 
        main0.run(applicationArguments0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // br/edu/ufcg/computacao/eureca/common/exceptions/FatalErrorException
         //
         verifyException("br.edu.ufcg.computacao.eureca.backend.Main", e);
      }
  }
}
