/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 05 23:02:33 GMT 2022
 */

package br.edu.ufcg.computacao.eureca.backend.constants;

import org.junit.Test;
import static org.junit.Assert.*;
import br.edu.ufcg.computacao.eureca.backend.constants.PortugueseSubjectsGlossary;
import br.edu.ufcg.computacao.eureca.backend.constants.SubjectsGlossaryFields;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PortugueseSubjectsGlossary_ESTest extends PortugueseSubjectsGlossary_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PortugueseSubjectsGlossary portugueseSubjectsGlossary0 = new PortugueseSubjectsGlossary();
      SubjectsGlossaryFields subjectsGlossaryFields0 = portugueseSubjectsGlossary0.getGlossary();
      assertNotNull(subjectsGlossaryFields0);
  }
}
