/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 05 23:35:15 GMT 2022
 */

package br.edu.ufcg.computacao.eureca.backend.api.http.response.enrollment;

import org.junit.Test;
import static org.junit.Assert.*;
import br.edu.ufcg.computacao.eureca.backend.api.http.response.enrollment.EnrollmentsMetricsPerTermSummary;
import br.edu.ufcg.computacao.eureca.backend.api.http.response.enrollment.EnrollmentsStatisticsResponse;
import java.util.Collection;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EnrollmentsStatisticsResponse_ESTest extends EnrollmentsStatisticsResponse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EnrollmentsStatisticsResponse enrollmentsStatisticsResponse0 = new EnrollmentsStatisticsResponse((Collection<EnrollmentsMetricsPerTermSummary>) null, "YH ,#o,+)?$fT9#2", "YH ,#o,+)?$fT9#2");
      String string0 = enrollmentsStatisticsResponse0.getCurriculumCode();
      assertEquals("YH ,#o,+)?$fT9#2", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EnrollmentsStatisticsResponse enrollmentsStatisticsResponse0 = new EnrollmentsStatisticsResponse((Collection<EnrollmentsMetricsPerTermSummary>) null, "YH ,#o,+)?$fT9#2", "YH ,#o,+)?$fT9#2");
      String string0 = enrollmentsStatisticsResponse0.getCourseCode();
      assertEquals("YH ,#o,+)?$fT9#2", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      EnrollmentsStatisticsResponse enrollmentsStatisticsResponse0 = new EnrollmentsStatisticsResponse((Collection<EnrollmentsMetricsPerTermSummary>) null, "", "");
      String string0 = enrollmentsStatisticsResponse0.getCourseCode();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      EnrollmentsStatisticsResponse enrollmentsStatisticsResponse0 = new EnrollmentsStatisticsResponse((Collection<EnrollmentsMetricsPerTermSummary>) null, (String) null, "");
      enrollmentsStatisticsResponse0.setEnrollmentsSummary((Collection<EnrollmentsMetricsPerTermSummary>) null);
      assertEquals("", enrollmentsStatisticsResponse0.getCurriculumCode());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      EnrollmentsStatisticsResponse enrollmentsStatisticsResponse0 = new EnrollmentsStatisticsResponse((Collection<EnrollmentsMetricsPerTermSummary>) null, (String) null, "");
      enrollmentsStatisticsResponse0.setCourseCode("eKuqAj");
      assertEquals("", enrollmentsStatisticsResponse0.getCurriculumCode());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      EnrollmentsStatisticsResponse enrollmentsStatisticsResponse0 = new EnrollmentsStatisticsResponse((Collection<EnrollmentsMetricsPerTermSummary>) null, "", "");
      enrollmentsStatisticsResponse0.setCurriculumCode((String) null);
      String string0 = enrollmentsStatisticsResponse0.getCurriculumCode();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      EnrollmentsStatisticsResponse enrollmentsStatisticsResponse0 = new EnrollmentsStatisticsResponse((Collection<EnrollmentsMetricsPerTermSummary>) null, (String) null, "");
      String string0 = enrollmentsStatisticsResponse0.getCurriculumCode();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      EnrollmentsStatisticsResponse enrollmentsStatisticsResponse0 = new EnrollmentsStatisticsResponse((Collection<EnrollmentsMetricsPerTermSummary>) null, (String) null, "");
      String string0 = enrollmentsStatisticsResponse0.getCourseCode();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      EnrollmentsStatisticsResponse enrollmentsStatisticsResponse0 = new EnrollmentsStatisticsResponse((Collection<EnrollmentsMetricsPerTermSummary>) null, (String) null, "");
      Collection<EnrollmentsMetricsPerTermSummary> collection0 = enrollmentsStatisticsResponse0.getEnrollmentsSummary();
      assertNull(collection0);
  }
}
