/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 13 21:34:31 GMT 2022
 */

package br.edu.ufcg.computacao.eureca.backend.api.http.response.preenrollment;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import br.edu.ufcg.computacao.eureca.backend.api.http.response.preenrollment.PreEnrollmentsResponse;
import br.edu.ufcg.computacao.eureca.backend.api.http.response.preenrollment.StudentPreEnrollmentResponse;
import br.edu.ufcg.computacao.eureca.backend.api.http.response.subject.SubjectDemandSummary;
import java.util.Collection;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PreEnrollmentsResponse_ESTest extends PreEnrollmentsResponse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PreEnrollmentsResponse preEnrollmentsResponse0 = new PreEnrollmentsResponse((Collection<StudentPreEnrollmentResponse>) null, (SubjectDemandSummary) null);
      SubjectDemandSummary subjectDemandSummary0 = preEnrollmentsResponse0.getSubjectDemandSummary();
      assertNull(subjectDemandSummary0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SubjectDemandSummary subjectDemandSummary0 = mock(SubjectDemandSummary.class, new ViolatedAssumptionAnswer());
      doReturn("x216bg-DRF-X?YI").when(subjectDemandSummary0).toString();
      PreEnrollmentsResponse preEnrollmentsResponse0 = new PreEnrollmentsResponse((Collection<StudentPreEnrollmentResponse>) null, subjectDemandSummary0);
      String string0 = preEnrollmentsResponse0.toString();
      assertEquals("PreEnrollmentsResponse{activesPreEnrollment=null, subjectDemandSummary=x216bg-DRF-X?YI}", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SubjectDemandSummary subjectDemandSummary0 = mock(SubjectDemandSummary.class, new ViolatedAssumptionAnswer());
      doReturn("x216bg-DRF-X?YI").when(subjectDemandSummary0).toString();
      PreEnrollmentsResponse preEnrollmentsResponse0 = new PreEnrollmentsResponse((Collection<StudentPreEnrollmentResponse>) null, subjectDemandSummary0);
      SubjectDemandSummary subjectDemandSummary1 = preEnrollmentsResponse0.getSubjectDemandSummary();
      preEnrollmentsResponse0.setSubjectDemandSummary(subjectDemandSummary1);
      assertSame(subjectDemandSummary1, subjectDemandSummary0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SubjectDemandSummary subjectDemandSummary0 = mock(SubjectDemandSummary.class, new ViolatedAssumptionAnswer());
      PreEnrollmentsResponse preEnrollmentsResponse0 = new PreEnrollmentsResponse((Collection<StudentPreEnrollmentResponse>) null, subjectDemandSummary0);
      Collection<StudentPreEnrollmentResponse> collection0 = preEnrollmentsResponse0.getActivesPreEnrollment();
      assertNull(collection0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SubjectDemandSummary subjectDemandSummary0 = mock(SubjectDemandSummary.class, new ViolatedAssumptionAnswer());
      PreEnrollmentsResponse preEnrollmentsResponse0 = new PreEnrollmentsResponse((Collection<StudentPreEnrollmentResponse>) null, subjectDemandSummary0);
      preEnrollmentsResponse0.setActivesPreEnrollment((Collection<StudentPreEnrollmentResponse>) null);
  }
}
