/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 13 21:32:42 GMT 2022
 */

package br.edu.ufcg.computacao.eureca.backend.api.http.response.active;

import org.junit.Test;
import static org.junit.Assert.*;
import br.edu.ufcg.computacao.eureca.backend.api.http.response.active.ActivesPerTermSummary;
import br.edu.ufcg.computacao.eureca.backend.api.http.response.active.ActivesStatisticsResponse;
import java.util.Collection;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ActivesStatisticsResponse_ESTest extends ActivesStatisticsResponse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ActivesStatisticsResponse activesStatisticsResponse0 = new ActivesStatisticsResponse((Collection<ActivesPerTermSummary>) null, (String) null, (String) null, "X\"Qk<@(eui\"3})", "tizckE");
      String string0 = activesStatisticsResponse0.getCurriculumCode();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ActivesStatisticsResponse activesStatisticsResponse0 = new ActivesStatisticsResponse((Collection<ActivesPerTermSummary>) null, "", "", "", "f[");
      String string0 = activesStatisticsResponse0.getCurriculumCode();
      assertEquals("", activesStatisticsResponse0.getCourseCode());
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ActivesStatisticsResponse activesStatisticsResponse0 = new ActivesStatisticsResponse((Collection<ActivesPerTermSummary>) null, (String) null, (String) null, "X\"Qk<@(eui\"3})", "tizckE");
      String string0 = activesStatisticsResponse0.getCourseCode();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ActivesStatisticsResponse activesStatisticsResponse0 = new ActivesStatisticsResponse((Collection<ActivesPerTermSummary>) null, ".\"\"$p7VP@ccJG6M", ".\"\"$p7VP@ccJG6M", ".\"\"$p7VP@ccJG6M", ".\"\"$p7VP@ccJG6M");
      String string0 = activesStatisticsResponse0.getCourseCode();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ActivesStatisticsResponse activesStatisticsResponse0 = new ActivesStatisticsResponse((Collection<ActivesPerTermSummary>) null, (String) null, (String) null, "X\"Qk<@(eui\"3})", "tizckE");
      activesStatisticsResponse0.setCourseCode((String) null);
      assertEquals("X\"Qk<@(eui\"3})", activesStatisticsResponse0.getFrom());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ActivesStatisticsResponse activesStatisticsResponse0 = new ActivesStatisticsResponse((Collection<ActivesPerTermSummary>) null, (String) null, (String) null, "X\"Qk<@(eui\"3})", "tizckE");
      Collection<ActivesPerTermSummary> collection0 = activesStatisticsResponse0.getActivesPerTermSummaries();
      assertNull(collection0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ActivesStatisticsResponse activesStatisticsResponse0 = new ActivesStatisticsResponse((Collection<ActivesPerTermSummary>) null, "7t6Nzj", "7t6Nzj", "CC?gOr!o=NM?xj% >/,", ";#9cw");
      String string0 = activesStatisticsResponse0.getCurriculumCode();
      assertEquals("7t6Nzj", string0);
      assertEquals("7t6Nzj", activesStatisticsResponse0.getCourseCode());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      ActivesStatisticsResponse activesStatisticsResponse0 = new ActivesStatisticsResponse((Collection<ActivesPerTermSummary>) null, (String) null, "%dC|k,n^+k", "br.edu.ufcg.computacao.eureca.backend.api.http.response.active.ActivesStatisticsResponse", "br.edu.ufcg.computacao.eureca.backend.api.http.response.active.ActivesStatisticsResponse");
      activesStatisticsResponse0.setCurriculumCode((String) null);
      assertEquals("br.edu.ufcg.computacao.eureca.backend.api.http.response.active.ActivesStatisticsResponse", activesStatisticsResponse0.getTo());
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      ActivesStatisticsResponse activesStatisticsResponse0 = new ActivesStatisticsResponse((Collection<ActivesPerTermSummary>) null, "", "", "", "br.edu.ufcg.computacao.eureca.backend.api.http.response.active.ActivesStatisticsResponse");
      String string0 = activesStatisticsResponse0.getCourseCode();
      assertEquals("", string0);
      assertEquals("", activesStatisticsResponse0.getCurriculumCode());
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      ActivesStatisticsResponse activesStatisticsResponse0 = new ActivesStatisticsResponse((Collection<ActivesPerTermSummary>) null, "", "", "", "br.edu.ufcg.computacao.eureca.backend.api.http.response.active.ActivesStatisticsResponse");
      activesStatisticsResponse0.setActivesPerTermSummaries((Collection<ActivesPerTermSummary>) null);
      assertEquals("", activesStatisticsResponse0.getCourseCode());
      assertEquals("", activesStatisticsResponse0.getCurriculumCode());
  }
}
