/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 05 23:38:05 GMT 2022
 */

package br.edu.ufcg.computacao.eureca.backend.core.dao.scsvfiles.mapentries;

import org.junit.Test;
import static org.junit.Assert.*;
import br.edu.ufcg.computacao.eureca.backend.core.dao.scsvfiles.mapentries.ProfileData;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ProfileData_ESTest extends ProfileData_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ProfileData profileData0 = new ProfileData();
      String string0 = profileData0.getCourseName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ProfileData profileData0 = new ProfileData();
      profileData0.setCourseName(")?1Uzg");
      String string0 = profileData0.getCourseName();
      assertEquals(")?1Uzg", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ProfileData profileData0 = new ProfileData();
      String string0 = profileData0.getCourseCode();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ProfileData profileData0 = new ProfileData("", "");
      profileData0.setCourseName("");
      assertEquals("", profileData0.getCourseName());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ProfileData profileData0 = new ProfileData("", "");
      profileData0.setCourseCode("G");
      assertEquals("", profileData0.getCourseName());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ProfileData profileData0 = new ProfileData("", "");
      String string0 = profileData0.getCourseCode();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ProfileData profileData0 = new ProfileData("", "");
      String string0 = profileData0.getCourseName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      ProfileData profileData0 = new ProfileData();
      profileData0.setCourseCode("pAGN\"'h");
      String string0 = profileData0.getCourseCode();
      assertEquals("pAGN\"'h", string0);
  }
}
