/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 13 21:29:17 GMT 2022
 */

package br.edu.ufcg.computacao.eureca.backend.core.models;

import org.junit.Test;
import static org.junit.Assert.*;
import br.edu.ufcg.computacao.eureca.backend.core.models.StudentStatus;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class StudentStatus_ESTest extends StudentStatus_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      StudentStatus[] studentStatusArray0 = StudentStatus.values();
      assertEquals(3, studentStatusArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      StudentStatus studentStatus0 = StudentStatus.valueOf("ACTIVE");
      assertEquals(StudentStatus.ACTIVE, studentStatus0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      StudentStatus studentStatus0 = StudentStatus.ALUMNUS;
      String string0 = studentStatus0.getValue();
      assertEquals("GRADUADO", string0);
  }
}
