/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 05 22:48:04 GMT 2022
 */

package br.edu.ufcg.computacao.eureca.backend.core.models;

import org.junit.Test;
import static org.junit.Assert.*;
import br.edu.ufcg.computacao.eureca.backend.core.models.SubjectType;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SubjectType_ESTest extends SubjectType_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SubjectType subjectType0 = SubjectType.toEnum("elective");
      assertEquals(SubjectType.ELECTIVE, subjectType0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SubjectType[] subjectTypeArray0 = SubjectType.values();
      assertEquals(5, subjectTypeArray0.length);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SubjectType subjectType0 = SubjectType.valueOf("ELECTIVE");
      assertEquals("elective", subjectType0.getValue());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SubjectType subjectType0 = SubjectType.ALL;
      String string0 = subjectType0.getValue();
      assertEquals("all", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SubjectType.toEnum("3H\"62$");
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SubjectType subjectType0 = SubjectType.toEnum("all");
      assertEquals(SubjectType.ALL, subjectType0);
  }
}
