/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 05 23:42:04 GMT 2022
 */

package br.edu.ufcg.computacao.eureca.backend.api.http.response.preenrollment;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import br.edu.ufcg.computacao.eureca.backend.api.http.response.preenrollment.DemandResponse;
import br.edu.ufcg.computacao.eureca.backend.api.http.response.subject.SubjectDemandSummary;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DemandResponse_ESTest extends DemandResponse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SubjectDemandSummary subjectDemandSummary0 = mock(SubjectDemandSummary.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(subjectDemandSummary0).toString();
      DemandResponse demandResponse0 = new DemandResponse(subjectDemandSummary0);
      SubjectDemandSummary subjectDemandSummary1 = demandResponse0.getSubjectDemandSummary();
      assertSame(subjectDemandSummary1, subjectDemandSummary0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DemandResponse demandResponse0 = new DemandResponse((SubjectDemandSummary) null);
      String string0 = demandResponse0.toString();
      assertEquals("PreEnrollments{, subjectDemandSummary=null}", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DemandResponse demandResponse0 = new DemandResponse((SubjectDemandSummary) null);
      SubjectDemandSummary subjectDemandSummary0 = demandResponse0.getSubjectDemandSummary();
      assertNull(subjectDemandSummary0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DemandResponse demandResponse0 = new DemandResponse((SubjectDemandSummary) null);
      demandResponse0.setSubjectDemandSummary((SubjectDemandSummary) null);
  }
}
