/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 05 23:23:37 GMT 2022
 */

package br.edu.ufcg.computacao.eureca.backend.api.http.response.preenrollment;

import org.junit.Test;
import static org.junit.Assert.*;
import br.edu.ufcg.computacao.eureca.backend.api.http.response.preenrollment.SubjectDemand;
import br.edu.ufcg.computacao.eureca.backend.api.http.response.preenrollment.SubjectsDemandResponse;
import java.util.Collection;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SubjectsDemandResponse_ESTest extends SubjectsDemandResponse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SubjectsDemandResponse subjectsDemandResponse0 = new SubjectsDemandResponse((Collection<SubjectDemand>) null);
      Collection<SubjectDemand> collection0 = subjectsDemandResponse0.getDemand();
      assertNull(collection0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SubjectsDemandResponse subjectsDemandResponse0 = new SubjectsDemandResponse((Collection<SubjectDemand>) null);
      subjectsDemandResponse0.setDemand((Collection<SubjectDemand>) null);
  }
}
