/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 05 23:34:06 GMT 2022
 */

package br.edu.ufcg.computacao.eureca.backend.api.http.response.dropout;

import org.junit.Test;
import static org.junit.Assert.*;
import br.edu.ufcg.computacao.eureca.backend.api.http.response.dropout.DropoutPerTermSummary;
import br.edu.ufcg.computacao.eureca.backend.api.http.response.dropout.DropoutsStatisticsResponse;
import java.util.Collection;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DropoutsStatisticsResponse_ESTest extends DropoutsStatisticsResponse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DropoutsStatisticsResponse dropoutsStatisticsResponse0 = new DropoutsStatisticsResponse((Collection<DropoutPerTermSummary>) null, "", "br.edu.ufcg.computacao.eureca.backend.api.http.response.dropout.DropoutsStatisticsResponse", "?mF,>))p{SMe.", "");
      String string0 = dropoutsStatisticsResponse0.getCurriculumCode();
      assertEquals("br.edu.ufcg.computacao.eureca.backend.api.http.response.dropout.DropoutsStatisticsResponse", string0);
      assertEquals("", dropoutsStatisticsResponse0.getCourseCode());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DropoutsStatisticsResponse dropoutsStatisticsResponse0 = new DropoutsStatisticsResponse((Collection<DropoutPerTermSummary>) null, (String) null, (String) null, "", "");
      dropoutsStatisticsResponse0.setCurriculumCode("");
      String string0 = dropoutsStatisticsResponse0.getCurriculumCode();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DropoutsStatisticsResponse dropoutsStatisticsResponse0 = new DropoutsStatisticsResponse((Collection<DropoutPerTermSummary>) null, (String) null, (String) null, "A6M3", "A6M3");
      String string0 = dropoutsStatisticsResponse0.getCourseCode();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DropoutsStatisticsResponse dropoutsStatisticsResponse0 = new DropoutsStatisticsResponse((Collection<DropoutPerTermSummary>) null, "br.edu.ufcg.computacao.eureca.backend.api.http.response.dropout.DropoutPerTermSummary", "br.edu.ufcg.computacao.eureca.backend.api.http.response.dropout.DropoutPerTermSummary", "Mm@mAFN", "Mm@mAFN");
      String string0 = dropoutsStatisticsResponse0.getCourseCode();
      assertEquals("br.edu.ufcg.computacao.eureca.backend.api.http.response.dropout.DropoutPerTermSummary", string0);
      assertEquals("br.edu.ufcg.computacao.eureca.backend.api.http.response.dropout.DropoutPerTermSummary", dropoutsStatisticsResponse0.getCurriculumCode());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      DropoutsStatisticsResponse dropoutsStatisticsResponse0 = new DropoutsStatisticsResponse((Collection<DropoutPerTermSummary>) null, (String) null, "", "", "");
      dropoutsStatisticsResponse0.setCourseCode("");
      assertEquals("", dropoutsStatisticsResponse0.getCurriculumCode());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      DropoutsStatisticsResponse dropoutsStatisticsResponse0 = new DropoutsStatisticsResponse((Collection<DropoutPerTermSummary>) null, "", "", "", "");
      String string0 = dropoutsStatisticsResponse0.getCourseCode();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      DropoutsStatisticsResponse dropoutsStatisticsResponse0 = new DropoutsStatisticsResponse((Collection<DropoutPerTermSummary>) null, (String) null, (String) null, "", "");
      dropoutsStatisticsResponse0.setDropoutPerTermSummaries((Collection<DropoutPerTermSummary>) null);
      assertNull(dropoutsStatisticsResponse0.getCurriculumCode());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      DropoutsStatisticsResponse dropoutsStatisticsResponse0 = new DropoutsStatisticsResponse((Collection<DropoutPerTermSummary>) null, (String) null, (String) null, "", "");
      String string0 = dropoutsStatisticsResponse0.getCurriculumCode();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      DropoutsStatisticsResponse dropoutsStatisticsResponse0 = new DropoutsStatisticsResponse((Collection<DropoutPerTermSummary>) null, (String) null, (String) null, "", "");
      Collection<DropoutPerTermSummary> collection0 = dropoutsStatisticsResponse0.getDropoutPerTermSummaries();
      assertNull(collection0);
  }
}
