/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 05 22:56:58 GMT 2022
 */

package br.edu.ufcg.computacao.eureca.backend.core.dao.scsvfiles.mapentries;

import org.junit.Test;
import static org.junit.Assert.*;
import br.edu.ufcg.computacao.eureca.backend.core.dao.scsvfiles.mapentries.AcademicUnitData;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AcademicUnitData_ESTest extends AcademicUnitData_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AcademicUnitData academicUnitData0 = new AcademicUnitData();
      String string0 = academicUnitData0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AcademicUnitData academicUnitData0 = new AcademicUnitData();
      academicUnitData0.setName("");
      String string0 = academicUnitData0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AcademicUnitData academicUnitData0 = new AcademicUnitData();
      String string0 = academicUnitData0.getAcronym();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      AcademicUnitData academicUnitData0 = new AcademicUnitData();
      academicUnitData0.setAcronym("tX4_;#<(y_:{=");
      String string0 = academicUnitData0.getAcronym();
      assertEquals("tX4_;#<(y_:{=", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      AcademicUnitData academicUnitData0 = new AcademicUnitData("br.edu.ufcg.computacao.eureca.backend.core.dao.scsvfiles.mapentries.AcademicUnitData", "br.edu.ufcg.computacao.eureca.backend.core.dao.scsvfiles.mapentries.AcademicUnitData");
      academicUnitData0.setName("");
      assertEquals("", academicUnitData0.getName());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      AcademicUnitData academicUnitData0 = new AcademicUnitData("br.edu.ufcg.computacao.eureca.backend.core.dao.scsvfiles.mapentries.AcademicUnitData", "br.edu.ufcg.computacao.eureca.backend.core.dao.scsvfiles.mapentries.AcademicUnitData");
      String string0 = academicUnitData0.getName();
      assertEquals("br.edu.ufcg.computacao.eureca.backend.core.dao.scsvfiles.mapentries.AcademicUnitData", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      AcademicUnitData academicUnitData0 = new AcademicUnitData("", "");
      String string0 = academicUnitData0.getAcronym();
      assertEquals("", string0);
  }
}
